pre-commit:
  parallel: true
  jobs:
    - name: encrypt-secrets
      glob: secrets/secrets.json
      run:  sops -e --output secrets/secrets.json.enc secrets/secrets.json

    - name: encrypt-profile0-wifi-psk
      glob: secrets/profile0-wifi-psk.txt
      run: sops -e --output secrets/profile0-wifi-psk.txt.enc secrets/profile0-wifi-psk.txt

# post-merge:
#   parallel: true
#   jobs:
#     - name: encrypt-secrets
#       glob: secrets/secrets.json
#       run: SOPS_AGE_KEY_FILE=~/.config/age/nixos-config.txt sops -i -d --output-type json secrets.json || { echo "SOPS decryption failed."; exit 1; }
