pre-commit:
  parallel: true
  jobs:
    - name: encrypt-secrets
      glob: secrets/secrets.json
      run: sops -d secrets/secrets.json &>/dev/null && echo "secrets.json is already encrypted, skipping" || sops -i -e secrets/secrets.json

    - name: encrypt-profile0-wifi-psk
      glob: secrets/profile0-wifi-psk.txt
      run: sops -d secrets/profile0-wifi-psk.txt &>/dev/null && echo "profile0-wifi-psk.txt is already encrypted, skipping" || sops -i -e secrets/profile0-wifi-psk.txt

# post-merge:
#   parallel: true
#   jobs:
#     - name: encrypt-secrets
#       glob: secrets/secrets.json
#       run: SOPS_AGE_KEY_FILE=~/.config/age/nixos-config.txt sops -i -d --output-type json secrets.json || { echo "SOPS decryption failed."; exit 1; }
