pre-commit:
  parallel: false
  commands:
    encrypt-everything:
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        # Enable globstar to recurse files
        # Enable nullglob so secrets/* expands to nothing if empty
        shopt -s globstar nullglob

        # 1) Encrypt & stage .enc files
        for src in secrets/*; do
          [[ -f "$src" ]] || continue
          [[ "$src" == *.enc ]] && continue
          dst="$src.enc"
          sops -e --output "$dst" "$src"
          git add "$dst"
        done

        # 2) Unstage everything except .enc
        #    Build a list of staged secret-files that do NOT end in .enc
        mapfile -t to_unstage < <(
          git diff --cached --name-only |
          grep '^secrets/'    |
          grep -v '\.enc$'
        )

        # If there are any, unstage them
        if (( ${#to_unstage[@]} )); then
          git restore --staged "${to_unstage[@]}"
        fi