# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &nixos-config age1ffmgz0asj0pj8jpem3rxus5luagf6g4t2npr0xq7vhgjm33n93uqqnzz97

creation_rules:
  - path_regex: \.autoenv(_leave)?\.zsh$
    key_groups:
    - age:
      - *nixos-config
  - path_regex: ^secrets\.json$
    key_groups:
    - age:
      - *nixos-config
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *nixos-config
